### ISSUE TITLE
Possíveis bases de dados

### ISSUE THREAD

**Issue by julia-tavares** [analise-viz-dados-1sem-2020/hw99-analise-viz-dados-grupo09#1]
Ei, gente!
Olhando as bases de dados disponíveis, encontrei duas que achei interessantes como possíveis escolhas para a análise. 
Vejam o que acham:

**Bolsas concedidas e perfil dos beneficiários do PROUNI**:
[http://dados.gov.br/dataset/mec-prouni](url)

**Remuneração dos servidores do Poder Executivo de MG**:
[http://www.transparencia.dadosabertos.mg.gov.br/dataset/remuneracao-dos-servidores/resource/917c65df-59ac-4b97-a0a1-d8927da5c15b](url)

**Comment by rodrigobp998** [comment]
Boa noite, prezados!

A base de dados que optamos, enquanto grupo, para análise de dados do trabalho proposto é a de "Bolsas concedidas e perfil dos beneficiários do PROUNI". Essa base de dados está disponível para acesso neste [link] (http://dados.gov.br/dataset/mec-prouni)

As perguntas que orientam a análise são:

· Qual o perfil demográfico dos bolsistas, no que se refere a gênero, raça, faixa etária e existência de deficiência?

· Como se dá a distribuição geográfica dos bolsistas por unidade federativa?

· Quais os 10 cursos que recebem mais bolsistas ProUni?

**Comment by rodrigobp998** [comment]
Boa noite, prezados!

A base de dados que optamos, enquanto grupo, para análise de dados do trabalho proposto é a de "Bolsas concedidas e perfil dos beneficiários do PROUNI". Essa base de dados está disponível para acesso neste [link](http://dados.gov.br/dataset/mec-prouni)

As perguntas que orientam a análise são:

· Qual o perfil demográfico dos bolsistas, no que se refere a gênero, raça, faixa etária e existência de deficiência?

· Como se dá a distribuição geográfica dos bolsistas por unidade federativa?

· Quais os 10 cursos que recebem mais bolsistas ProUni?
